# Generated by Django 4.2.7 on 2025-07-09 10:59

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple] = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_id",
                    models.CharField(max_length=20, unique=True, verbose_name="房间ID"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="房间名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, verbose_name="房间描述"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("random", "随机匹配"),
                            ("filtered", "条件匹配"),
                            ("private", "私密房间"),
                            ("group", "群组房间"),
                        ],
                        default="random",
                        max_length=20,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待中"),
                            ("matching", "匹配中"),
                            ("connected", "已连接"),
                            ("disconnected", "已断开"),
                            ("closed", "已关闭"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="房间状态",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="最大参与人数",
                    ),
                ),
                (
                    "target_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                        ],
                        max_length=10,
                        verbose_name="目标性别",
                    ),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="最小年龄",
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="最大年龄",
                    ),
                ),
                (
                    "location_preference",
                    models.CharField(blank=True, max_length=100, verbose_name="地区偏好"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="是否私密"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "total_visitors",
                    models.IntegerField(default=0, verbose_name="总访客数"),
                ),
                (
                    "total_connections",
                    models.IntegerField(default=0, verbose_name="总连接数"),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="平均评分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="最后活动时间"),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
                "db_table": "rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("matched", "已匹配"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="匹配状态",
                    ),
                ),
                (
                    "requested_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                        ],
                        max_length=10,
                        verbose_name="请求性别",
                    ),
                ),
                (
                    "min_age",
                    models.IntegerField(blank=True, null=True, verbose_name="最小年龄"),
                ),
                (
                    "max_age",
                    models.IntegerField(blank=True, null=True, verbose_name="最大年龄"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "matched_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="匹配时间"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
            ],
            options={
                "verbose_name": "房间匹配",
                "verbose_name_plural": "房间匹配",
                "db_table": "room_matches",
            },
        ),
        migrations.CreateModel(
            name="RoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "房主"),
                            ("participant", "参与者"),
                            ("spectator", "观众"),
                        ],
                        default="participant",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待中"),
                            ("connected", "已连接"),
                            ("disconnected", "已断开"),
                            ("left", "已离开"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, max_length=100, verbose_name="会话ID"),
                ),
                (
                    "connection_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="连接时间"),
                ),
                (
                    "disconnect_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="断开时间"),
                ),
                (
                    "total_time",
                    models.IntegerField(default=0, verbose_name="总参与时间(秒)"),
                ),
                (
                    "rating_given",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="给出的评分",
                    ),
                ),
                (
                    "rating_received",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="收到的评分",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "房间参与者",
                "verbose_name_plural": "房间参与者",
                "db_table": "room_participants",
            },
        ),
        migrations.CreateModel(
            name="RoomRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, max_length=500, verbose_name="评价"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "房间评分",
                "verbose_name_plural": "房间评分",
                "db_table": "room_ratings",
            },
        ),
        migrations.CreateModel(
            name="RoomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("inappropriate", "不当内容"),
                            ("harassment", "骚扰行为"),
                            ("spam", "垃圾信息"),
                            ("fake", "虚假信息"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="举报描述"),
                ),
                (
                    "evidence",
                    models.JSONField(default=list, verbose_name="证据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("investigating", "调查中"),
                            ("resolved", "已处理"),
                            ("dismissed", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="管理员备注"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="举报时间"),
                ),
            ],
            options={
                "verbose_name": "房间举报",
                "verbose_name_plural": "房间举报",
                "db_table": "room_reports",
            },
        ),
    ]







