# Generated by Django 4.2.7 on 2025-07-09 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roomreport",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="roomreport",
            name="reported_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被举报用户",
            ),
        ),
        migrations.AddField(
            model_name="roomreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_filed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="举报人",
            ),
        ),
        migrations.AddField(
            model_name="roomreport",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="roomrating",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评分用户",
            ),
        ),
        migrations.AddField(
            model_name="roomrating",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="roomrating",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被评分用户",
            ),
        ),
        migrations.AddField(
            model_name="roomparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="roomparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="roommatch",
            name="matched_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="匹配用户",
            ),
        ),
        migrations.AddField(
            model_name="roommatch",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="roommatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["room_id"], name="rooms_room_id_331bb5_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["room_type"], name="rooms_room_ty_7b8350_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["status"], name="rooms_status_ee4627_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["is_active"], name="rooms_is_acti_b7cb02_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["created_at"], name="rooms_created_3ab07f_idx"),
        ),
        migrations.AddIndex(
            model_name="roomreport",
            index=models.Index(
                fields=["room", "reporter", "reported_user"],
                name="room_report_room_id_77c2f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roomreport",
            index=models.Index(fields=["report_type"], name="room_report_report__127c27_idx"),
        ),
        migrations.AddIndex(
            model_name="roomreport",
            index=models.Index(fields=["status"], name="room_report_status_66b7d8_idx"),
        ),
        migrations.AddIndex(
            model_name="roomreport",
            index=models.Index(fields=["created_at"], name="room_report_created_652038_idx"),
        ),
        migrations.AddIndex(
            model_name="roomrating",
            index=models.Index(
                fields=["room", "from_user", "to_user"],
                name="room_rating_room_id_e57bac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roomrating",
            index=models.Index(fields=["rating"], name="room_rating_rating_dc8d54_idx"),
        ),
        migrations.AddIndex(
            model_name="roomrating",
            index=models.Index(fields=["created_at"], name="room_rating_created_34ec12_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roomrating",
            unique_together={("room", "from_user", "to_user")},
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["room", "user"], name="room_partic_room_id_8ba6aa_idx"),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["status"], name="room_partic_status_08f239_idx"),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["is_active"], name="room_partic_is_acti_a731be_idx"),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(fields=["joined_at"], name="room_partic_joined__7f85b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roomparticipant",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="roommatch",
            index=models.Index(fields=["room", "user"], name="room_matche_room_id_dfbb31_idx"),
        ),
        migrations.AddIndex(
            model_name="roommatch",
            index=models.Index(fields=["status"], name="room_matche_status_7ccf11_idx"),
        ),
        migrations.AddIndex(
            model_name="roommatch",
            index=models.Index(fields=["created_at"], name="room_matche_created_12e3d9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roommatch",
            unique_together={("room", "user")},
        ),
    ]
