# Generated by Django 4.2.7 on 2025-07-09 10:59

import uuid

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="请输入正确的手机号码",
                                regex="^1[3-9]\\d{9}$",
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                        ],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="个人简介"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="所在地"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "普通用户"),
                            ("host", "主播"),
                            ("admin", "管理员"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("inactive", "未激活"),
                            ("banned", "封禁"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否实名认证"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="是否在线"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="最后登录IP"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后活动时间"),
                ),
                (
                    "total_calls",
                    models.IntegerField(default=0, verbose_name="总通话次数"),
                ),
                (
                    "total_duration",
                    models.IntegerField(default=0, verbose_name="总通话时长(分钟)"),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="总收益",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="总消费",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(max_length=50, verbose_name="真实姓名"),
                ),
                (
                    "id_card",
                    models.CharField(max_length=18, verbose_name="身份证号"),
                ),
                (
                    "id_card_front",
                    models.ImageField(upload_to="verifications/", verbose_name="身份证正面"),
                ),
                (
                    "id_card_back",
                    models.ImageField(upload_to="verifications/", verbose_name="身份证背面"),
                ),
                (
                    "selfie",
                    models.ImageField(upload_to="verifications/", verbose_name="自拍照"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="管理员备注"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户认证",
                "verbose_name_plural": "用户认证",
                "db_table": "user_verifications",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="身高(cm)"),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="体重(kg)"),
                ),
                (
                    "education",
                    models.CharField(blank=True, max_length=50, verbose_name="学历"),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, max_length=100, verbose_name="职业"),
                ),
                (
                    "income",
                    models.CharField(blank=True, max_length=50, verbose_name="收入水平"),
                ),
                (
                    "hobbies",
                    models.JSONField(default=list, verbose_name="兴趣爱好"),
                ),
                (
                    "languages",
                    models.JSONField(default=list, verbose_name="语言能力"),
                ),
                (
                    "wechat",
                    models.CharField(blank=True, max_length=50, verbose_name="微信号"),
                ),
                (
                    "qq",
                    models.CharField(blank=True, max_length=20, verbose_name="QQ号"),
                ),
                (
                    "real_name",
                    models.CharField(blank=True, max_length=50, verbose_name="真实姓名"),
                ),
                (
                    "id_card",
                    models.CharField(blank=True, max_length=18, verbose_name="身份证号"),
                ),
                (
                    "id_card_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="id_cards/",
                        verbose_name="身份证正面",
                    ),
                ),
                (
                    "id_card_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="id_cards/",
                        verbose_name="身份证背面",
                    ),
                ),
                (
                    "is_host",
                    models.BooleanField(default=False, verbose_name="是否主播"),
                ),
                (
                    "host_level",
                    models.IntegerField(default=1, verbose_name="主播等级"),
                ),
                (
                    "host_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="主播评分",
                    ),
                ),
                (
                    "host_tags",
                    models.JSONField(default=list, verbose_name="主播标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=100, verbose_name="设备ID"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, verbose_name="设备名称"),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, verbose_name="设备型号"),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, max_length=50, verbose_name="系统版本"),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, max_length=20, verbose_name="应用版本"),
                ),
                (
                    "fcm_token",
                    models.CharField(blank=True, max_length=255, verbose_name="FCM推送令牌"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now_add=True, verbose_name="最后登录时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设备",
                "verbose_name_plural": "用户设备",
                "db_table": "user_devices",
                "unique_together": {("user", "device_id")},
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_phone_af6883_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="users_status_9ca66f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_online"], name="users_is_onli_f24b46_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
