# Generated by Django 4.2.7 on 2025-07-09 10:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "__first__"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "房主"),
                            ("admin", "管理员"),
                            ("member", "成员"),
                            ("guest", "访客"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("muted", "禁言"),
                            ("banned", "封禁"),
                            ("left", "已离开"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "can_send_message",
                    models.BooleanField(default=True, verbose_name="可发送消息"),
                ),
                (
                    "can_invite",
                    models.BooleanField(default=True, verbose_name="可邀请用户"),
                ),
                (
                    "can_manage",
                    models.BooleanField(default=False, verbose_name="可管理房间"),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="发送消息数"),
                ),
                (
                    "join_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "聊天参与者",
                "verbose_name_plural": "聊天参与者",
                "db_table": "chat_participants",
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "custom_room_id",
                    models.CharField(max_length=50, unique=True, verbose_name="房间ID"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="房间名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="房间描述"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "私聊"),
                            ("group", "群聊"),
                            ("room", "房间聊天"),
                            ("system", "系统消息"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("archived", "已归档"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="房间状态",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="是否私密"),
                ),
                (
                    "max_participants",
                    models.IntegerField(default=100, verbose_name="最大参与人数"),
                ),
                (
                    "allow_join",
                    models.BooleanField(default=True, verbose_name="允许加入"),
                ),
                (
                    "allow_message",
                    models.BooleanField(default=True, verbose_name="允许发送消息"),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="消息数量"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后消息时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chat_rooms",
                        through="chat.ChatParticipant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="rooms.room",
                        verbose_name="关联房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天房间",
                "verbose_name_plural": "聊天房间",
                "db_table": "chat_rooms",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(max_length=50, unique=True, verbose_name="消息ID"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("file", "文件"),
                            ("location", "位置"),
                            ("system", "系统消息"),
                            ("gift", "礼物"),
                            ("call", "通话"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "已发送"),
                            ("delivered", "已送达"),
                            ("read", "已读"),
                            ("failed", "发送失败"),
                            ("deleted", "已删除"),
                            ("recalled", "已撤回"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, verbose_name="媒体URL"),
                ),
                (
                    "media_path",
                    models.CharField(blank=True, max_length=500, verbose_name="媒体路径"),
                ),
                (
                    "media_size",
                    models.BigIntegerField(default=0, verbose_name="媒体大小(字节)"),
                ),
                (
                    "media_duration",
                    models.IntegerField(default=0, verbose_name="媒体时长(秒)"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="是否编辑"),
                ),
                (
                    "is_reply",
                    models.BooleanField(default=False, verbose_name="是否回复"),
                ),
                (
                    "is_forwarded",
                    models.BooleanField(default=False, verbose_name="是否转发"),
                ),
                (
                    "forwarded_from",
                    models.CharField(blank=True, max_length=255, verbose_name="转发来源"),
                ),
                (
                    "read_count",
                    models.IntegerField(default=0, verbose_name="已读人数"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="送达时间"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                        verbose_name="聊天房间",
                    ),
                ),
                (
                    "original_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forwarded_messages",
                        to="chat.message",
                        verbose_name="原消息",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.message",
                        verbose_name="回复消息",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_participants",
                to="chat.chatroom",
                verbose_name="聊天房间",
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="ChatNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "新消息"),
                            ("mention", "提及"),
                            ("invitation", "邀请"),
                            ("system", "系统通知"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="通知标题"),
                ),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("archived", "已归档"),
                        ],
                        default="unread",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_push",
                    models.BooleanField(default=True, verbose_name="推送通知"),
                ),
                (
                    "is_email",
                    models.BooleanField(default=False, verbose_name="邮件通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.chatroom",
                        verbose_name="聊天房间",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.message",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天通知",
                "verbose_name_plural": "聊天通知",
                "db_table": "chat_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, max_length=200, verbose_name="邀请消息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="响应时间"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="chat.chatroom",
                        verbose_name="聊天房间",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_chat_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被邀请者",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请者",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天邀请",
                "verbose_name_plural": "聊天邀请",
                "db_table": "chat_invitations",
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="阅读时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_records",
                        to="chat.message",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息已读记录",
                "verbose_name_plural": "消息已读记录",
                "db_table": "message_reads",
                "indexes": [
                    models.Index(
                        fields=["message", "user"],
                        name="message_rea_message_19da3c_idx",
                    ),
                    models.Index(
                        fields=["read_at"],
                        name="message_rea_read_at_625c1c_idx",
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.CreateModel(
            name="MessageLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="chat.message",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息点赞",
                "verbose_name_plural": "消息点赞",
                "db_table": "message_likes",
                "indexes": [
                    models.Index(
                        fields=["message", "user"],
                        name="message_lik_message_114be7_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="message_lik_created_17df88_idx",
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.CreateModel(
            name="MessageFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="chat.message",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息收藏",
                "verbose_name_plural": "消息收藏",
                "db_table": "message_favorites",
                "indexes": [
                    models.Index(
                        fields=["message", "user"],
                        name="message_fav_message_2385ef_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="message_fav_created_d44d58_idx",
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["message_id"], name="messages_message_83462e_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_room", "created_at"],
                name="messages_chat_ro_6c0442_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"],
                name="messages_sender__bf8b1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["message_type"], name="messages_message_5af74b_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="messages_status_72d01d_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["created_at"], name="messages_created_919c58_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["custom_room_id"], name="chat_rooms_custom__8855e8_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["room_type"], name="chat_rooms_room_ty_c8c67a_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["status"], name="chat_rooms_status_0c6d66_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["created_at"], name="chat_rooms_created_108bfd_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["last_message_at"],
                name="chat_rooms_last_me_a06a9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["chat_room", "user"],
                name="chat_partic_chat_ro_329d69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["role"], name="chat_partic_role_dd1543_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["status"], name="chat_partic_status_a4b4d1_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["is_active"], name="chat_partic_is_acti_6c8df5_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["join_time"], name="chat_partic_join_ti_20505e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("chat_room", "user")},
        ),
        migrations.AddIndex(
            model_name="chatnotification",
            index=models.Index(
                fields=["user", "status"],
                name="chat_notifi_user_id_4714a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatnotification",
            index=models.Index(
                fields=["notification_type"],
                name="chat_notifi_notific_a21a19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatnotification",
            index=models.Index(fields=["created_at"], name="chat_notifi_created_5047b7_idx"),
        ),
        migrations.AddIndex(
            model_name="chatinvitation",
            index=models.Index(
                fields=["chat_room", "inviter", "invitee"],
                name="chat_invita_chat_ro_a294fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatinvitation",
            index=models.Index(fields=["status"], name="chat_invita_status_4046aa_idx"),
        ),
        migrations.AddIndex(
            model_name="chatinvitation",
            index=models.Index(fields=["created_at"], name="chat_invita_created_0bc274_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chatinvitation",
            unique_together={("chat_room", "inviter", "invitee")},
        ),
    ]
