# Generated by Django 4.2.7 on 2025-07-09 10:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple] = []

    operations = [
        migrations.CreateModel(
            name="CallInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, max_length=200, verbose_name="邀请消息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="响应时间"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
            ],
            options={
                "verbose_name": "通话邀请",
                "verbose_name_plural": "通话邀请",
                "db_table": "call_invitations",
            },
        ),
        migrations.CreateModel(
            name="CallParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "主持人"),
                            ("participant", "参与者"),
                            ("spectator", "观众"),
                        ],
                        default="participant",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "已邀请"),
                            ("joined", "已加入"),
                            ("left", "已离开"),
                            ("rejected", "已拒绝"),
                        ],
                        default="invited",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "connection_id",
                    models.CharField(blank=True, max_length=100, verbose_name="连接ID"),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="设备信息"),
                ),
                (
                    "network_info",
                    models.JSONField(default=dict, verbose_name="网络信息"),
                ),
                (
                    "has_video",
                    models.BooleanField(default=True, verbose_name="开启视频"),
                ),
                (
                    "has_audio",
                    models.BooleanField(default=True, verbose_name="开启音频"),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="是否静音"),
                ),
                (
                    "is_camera_off",
                    models.BooleanField(default=False, verbose_name="摄像头关闭"),
                ),
                (
                    "join_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="加入时间"),
                ),
                (
                    "leave_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="离开时间"),
                ),
                (
                    "total_time",
                    models.IntegerField(default=0, verbose_name="参与时长(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通话参与者",
                "verbose_name_plural": "通话参与者",
                "db_table": "call_participants",
            },
        ),
        migrations.CreateModel(
            name="CallQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "video_quality",
                    models.DecimalField(decimal_places=2, max_digits=3, verbose_name="视频质量"),
                ),
                (
                    "audio_quality",
                    models.DecimalField(decimal_places=2, max_digits=3, verbose_name="音频质量"),
                ),
                (
                    "network_quality",
                    models.DecimalField(decimal_places=2, max_digits=3, verbose_name="网络质量"),
                ),
                (
                    "overall_quality",
                    models.DecimalField(decimal_places=2, max_digits=3, verbose_name="整体质量"),
                ),
                ("bitrate", models.IntegerField(verbose_name="比特率(Kbps)")),
                (
                    "packet_loss",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="丢包率(%)",
                    ),
                ),
                ("latency", models.IntegerField(verbose_name="延迟(ms)")),
                ("jitter", models.IntegerField(verbose_name="抖动(ms)")),
                (
                    "errors",
                    models.JSONField(default=list, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "通话质量",
                "verbose_name_plural": "通话质量",
                "db_table": "call_quality",
            },
        ),
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recording_id",
                    models.CharField(max_length=100, unique=True, verbose_name="录制ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "录制中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("deleted", "已删除"),
                        ],
                        default="recording",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="录制时长(秒)"),
                ),
                (
                    "include_video",
                    models.BooleanField(default=True, verbose_name="包含视频"),
                ),
                (
                    "include_audio",
                    models.BooleanField(default=True, verbose_name="包含音频"),
                ),
                (
                    "quality",
                    models.CharField(default="720p", max_length=20, verbose_name="录制质量"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "can_download",
                    models.BooleanField(default=False, verbose_name="允许下载"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
            ],
            options={
                "verbose_name": "通话录制",
                "verbose_name_plural": "通话录制",
                "db_table": "call_recordings",
            },
        ),
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=50, unique=True, verbose_name="会话ID"),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("video", "视频通话"),
                            ("audio", "语音通话"),
                            ("group_video", "群组视频"),
                            ("group_audio", "群组语音"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="通话类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiating", "发起中"),
                            ("ringing", "响铃中"),
                            ("connected", "已连接"),
                            ("disconnected", "已断开"),
                            ("missed", "未接"),
                            ("rejected", "已拒绝"),
                            ("busy", "忙线"),
                            ("ended", "已结束"),
                        ],
                        default="initiating",
                        max_length=20,
                        verbose_name="通话状态",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="是否私密"),
                ),
                (
                    "is_recorded",
                    models.BooleanField(default=False, verbose_name="是否录制"),
                ),
                (
                    "max_duration",
                    models.IntegerField(default=3600, verbose_name="最大时长(秒)"),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="通话时长(秒)"),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        verbose_name="质量评分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通话会话",
                "verbose_name_plural": "通话会话",
                "db_table": "call_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]






