# Generated by Django 4.2.7 on 2025-07-09 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("calls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发起者",
            ),
        ),
        migrations.AddField(
            model_name="callsession",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_calls",
                through="calls.CallParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与者",
            ),
        ),
        migrations.AddField(
            model_name="callsession",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sessions",
                to="rooms.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="call_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="calls.callsession",
                verbose_name="通话会话",
            ),
        ),
        migrations.AddField(
            model_name="callquality",
            name="call_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_records",
                to="calls.callsession",
                verbose_name="通话会话",
            ),
        ),
        migrations.AddField(
            model_name="callquality",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_records",
                to="calls.callparticipant",
                verbose_name="参与者",
            ),
        ),
        migrations.AddField(
            model_name="callparticipant",
            name="call_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_participants",
                to="calls.callsession",
                verbose_name="通话会话",
            ),
        ),
        migrations.AddField(
            model_name="callparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="callinvitation",
            name="call_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="calls.callsession",
                verbose_name="通话会话",
            ),
        ),
        migrations.AddField(
            model_name="callinvitation",
            name="invitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被邀请者",
            ),
        ),
        migrations.AddField(
            model_name="callinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请者",
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(fields=["session_id"], name="call_sessio_session_546c67_idx"),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(fields=["call_type"], name="call_sessio_call_ty_3ccf3b_idx"),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(fields=["status"], name="call_sessio_status_eae999_idx"),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(fields=["created_at"], name="call_sessio_created_5acdfc_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecording",
            index=models.Index(fields=["recording_id"], name="call_record_recordi_fc1a3d_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecording",
            index=models.Index(fields=["status"], name="call_record_status_128bbb_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecording",
            index=models.Index(fields=["started_at"], name="call_record_started_92e769_idx"),
        ),
        migrations.AddIndex(
            model_name="callquality",
            index=models.Index(
                fields=["call_session", "participant"],
                name="call_qualit_call_se_110a83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callquality",
            index=models.Index(fields=["timestamp"], name="call_qualit_timesta_6c37f8_idx"),
        ),
        migrations.AddIndex(
            model_name="callparticipant",
            index=models.Index(
                fields=["call_session", "user"],
                name="call_partic_call_se_178f30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callparticipant",
            index=models.Index(fields=["status"], name="call_partic_status_d00a7b_idx"),
        ),
        migrations.AddIndex(
            model_name="callparticipant",
            index=models.Index(fields=["is_active"], name="call_partic_is_acti_2887f1_idx"),
        ),
        migrations.AddIndex(
            model_name="callparticipant",
            index=models.Index(fields=["created_at"], name="call_partic_created_934577_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="callparticipant",
            unique_together={("call_session", "user")},
        ),
        migrations.AddIndex(
            model_name="callinvitation",
            index=models.Index(
                fields=["call_session", "inviter", "invitee"],
                name="call_invita_call_se_79cb52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callinvitation",
            index=models.Index(fields=["status"], name="call_invita_status_13bff9_idx"),
        ),
        migrations.AddIndex(
            model_name="callinvitation",
            index=models.Index(fields=["created_at"], name="call_invita_created_c86108_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="callinvitation",
            unique_together={("call_session", "inviter", "invitee")},
        ),
    ]
